Add new target config TAKER F411/config.h
betaflight/config pull request #154
Opened 2023-08-29 02:42 UTC by hakrc1

Add new target config TAKER F411/config.h

2023-08-29 11:29 UTC, haslinghuis requested changes

2023-08-29 11:29 UTC, haslinghuis commented on configs/TAKER F411/config.h
> +#define BOARD_NAME                      TAKER F411
```suggestion
#define BOARD_NAME                      TAKERF411
```

2023-08-29 11:29 UTC, haslinghuis commented on configs/TAKER F411/config.h
> +                                        TIMER_PIN_MAP( 4, PA8, 1,  0)
Have not compared with unified target timers and dma

```suggestion
                                        TIMER_PIN_MAP( 5, PA8, 1,  0)
```

2023-08-30 01:59 UTC, closed without merging

2023-08-30 12:46 UTC, nerdCopter commented
rather than closing PR's and creating new PR's for the same thing, it would preferred to simply fix it and push new commit.  could also squash and force-push.