Add FreeAxisF4 target
betaflight/config pull request #199
Opened 2023-10-26 22:37 UTC by ot0tot

Adds target for FreeAxis F4 25A AIO FC based on MATEKF411 target with the addition of a flash chip and BMI270.

Needs to be tested, gyro orientation verified, and FreeAxis vendor/board name approved. 

Solves: https://github.com/betaflight/unified-targets/issues/1149

Discord issue: https://discord.com/channels/868013470023548938/1160296288609390592

Thanks to J. R. @sixtyfive for the factory config https://discord.com/channels/868013470023548938/868013470518505494/1167219861601124392

2023-10-27 18:18 UTC, nerdCopter commented
![image](https://github.com/betaflight/config/assets/56646290/064fd655-bd2a-444a-b4d7-4f25a8325e3d)

recommended:

windows:
```
# git config --global core.autocrlf true
```
linux/osx:
```
git config --global core.autocrlf input
```

cross-platform:
```
git config --global core.safecrlf warn
git config --global core.whitespace cr-at-eol
git config --global core.filemode false
git config --global help.autocorrect true
```

2023-10-27 18:29 UTC, nerdCopter commented
@haslinghuis 
`#define MANUFACTURER_ID   FRXS`
not an official listing yet.  believe they are "Cloners"

2023-10-27 18:47 UTC, haslinghuis commented
You were reading my mind :)

See https://github.com/betaflight/unified-targets/pull/1173#discussion_r1374932807

2023-10-27 19:13 UTC, ot0tot commented
> ![image](https://user-images.githubusercontent.com/56646290/278725548-064fd655-bd2a-444a-b4d7-4f25a8325e3d.png)
> 
> recommended:
> 
> windows:
> 
> ```
> # git config --global core.autocrlf true
> ```
> 
> linux/osx:
> 
> ```
> git config --global core.autocrlf input
> ```
> 
> cross-platform:
> 
> ```
> git config --global core.safecrlf warn
> git config --global core.whitespace cr-at-eol
> git config --global core.filemode false
> git config --global help.autocorrect true
> ```

Resolved

2023-10-28 20:12 UTC, haslinghuis requested changes

2023-10-28 20:12 UTC, haslinghuis commented on configs/FREEAXISF4/config.h
> +#define DEFAULT_BARO_DEVICE BARO_NONE
Why set to none?
Also we should make the flash default:

```suggestion
#define DEFAULT_BLACKBOX_DEVICE BLACKBOX_DEVICE_FLASH
```

2023-10-28 20:12 UTC, haslinghuis commented on configs/FREEAXISF4/config.h
> +#define USE_BARO
Please move to line 34 before `#define USE_BARO_BMP280`

```suggestion
```

2023-10-28 20:42 UTC, haslinghuis submitted a review, later dismissed

2023-10-28 21:09 UTC, haslinghuis commented on configs/FREEAXISF4/config.h
> +#define USE_BARO
When remove the BARO specfic driver we also should remove this line :)
```suggestion
```

2023-10-28 21:14 UTC, haslinghuis commented on configs/FREEAXISF4/config.h
> +#define USE_BARO
Using this define defies cloud build as we try to isolate code to get maximum space for future development. There has been a lot of effort to configure only the drivers physical present.

2023-10-29 19:13 UTC, haslinghuis approved these changes

2023-10-29 19:15 UTC, merged