MAMBAF435_2023A fix dma, delete uart7
betaflight/config pull request #426
Opened 2024-05-17 09:54 UTC by x4FF3

hi,

fix for support id: 5c6a8d8d-e2b0-4000-8d35-db2870a17f26

KR
David

2024-05-17 10:37 UTC, haslinghuis approved these changes

2024-05-17 12:47 UTC, nerdCopter approved these changes

2024-05-17 22:44 UTC, haslinghuis requested changes
There is still doubt and confusion as there seems different board revisions available already resulting in support issues.

Working with Diatone to resolve this.

2024-06-14 17:39 UTC, ot0tot commented
Target was removed in https://github.com/betaflight/config/pull/428 
This should be closed.

2024-06-14 17:42 UTC, closed without merging