add GOODRONEF405
betaflight/config pull request #449
Opened 2024-06-03 13:21 UTC by nerdCopter

* add GOODRONEF405
* PR on behalf of @apexaxx
* needs review
* fixes #447

2024-06-03 13:35 UTC, haslinghuis approved these changes

2024-07-01 15:25 UTC, haslinghuis requested changes

2024-07-01 15:25 UTC, haslinghuis commented on configs/GOODRONEF405/config.h
> +#define SDCARD_DETECT_PIN    PB7
Does this target have both FLASH chip and SDCARD ?

2024-07-01 15:39 UTC, nerdCopter commented
in consideration of new policies, recommend closing this and forcing @apexaxx to solve own problems.

2024-07-01 16:01 UTC, haslinghuis commented
Closing as design does not comply with the target submission policy: https://betaflight.com/docs/development/manufacturer/requirements-for-submission-of-targets

2024-07-01 16:01 UTC, closed without merging