Create YYRC-EAGLEF722V0
betaflight/config pull request #465
Opened 2024-06-16 14:48 UTC by tianv2mu0897

Hello, I would like to create a branch and look forward to merging it; As I am creating it for the first time, if there are any issues, I am very much looking forward to you telling me the problem points; Thank you!

2024-06-17 14:19 UTC, nerdCopter commented on configs/YYRC-EAGLEF722V0
> +#define MANUFACTURER_ID   YYRC
`YYRC` will need to be added to https://github.com/betaflight/config/blob/master/Manufacturers.md

2024-06-18 14:29 UTC, nerdCopter commented
@tianv2mu0897 , may need to provide schematics and samples to dev-team.  may need to join Discord and contact @sugaarK for such.

2024-06-18 14:43 UTC, nerdCopter commented on configs/YYRC-EAGLEF722V0
> +#define MANUFACTURER_ID   YYRC
https://github.com/betaflight/config/pull/463

2024-06-18 15:31 UTC, haslinghuis requested changes

2024-06-18 15:31 UTC, haslinghuis commented on configs/YYRC-EAGLEF722V0
> +#define PINIO2_BOX 40
No PINIO pins defined.

```suggestion
```

2024-06-18 15:31 UTC, haslinghuis commented on configs/YYRC-EAGLEF722V0
> +#define USE_BARO
Duplicate define
```suggestion
```

2024-06-18 15:45 UTC, tianv2mu0897 commented
hello:
&nbsp; &nbsp; &nbsp; &nbsp; I have updated it;


【天v2幕】
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "betaflight/config"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年6月18日(星期二) 晚上11:31
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [betaflight/config] Create YYRC-EAGLEF722 (PR #465)





 
@haslinghuis requested changes on this pull request.
 
 
In configs/YYRC-EAGLEF722V0:
 &gt; +#define PINIO1_CONFIG 129 +#define PINIO2_CONFIG 129 +#define PINIO1_BOX 0 +#define PINIO2_BOX 40  
No PINIO pins defined.
 ⬇️ Suggested change -#define PINIO1_CONFIG 129 -#define PINIO2_CONFIG 129 -#define PINIO1_BOX 0 -#define PINIO2_BOX 40  
 
In configs/YYRC-EAGLEF722V0:
 &gt; +#define GYRO_1_CS_PIN PA0 +#define USB_DETECT_PIN PA10 +#define PULLDOWN_PIN_UART1 PC0 + +#define TIMER_PIN_MAPPING \ +    TIMER_PIN_MAP( 0, PB9 , 2, -1) \ +    TIMER_PIN_MAP( 1, PC8 , 2,  0) \ +    TIMER_PIN_MAP( 2, PC9 , 2,  0) \ +    TIMER_PIN_MAP( 3, PA8 , 1,  0) \ +    TIMER_PIN_MAP( 4, PA9 , 1,  0) \ +    TIMER_PIN_MAP( 6, PB3 , 1,  0) \ + +#define ADC1_DMA_OPT        0 + +#define MAG_I2C_INSTANCE (I2CDEV_1) +#define USE_BARO  
Duplicate define
 ⬇️ Suggested change -#define USE_BARO  
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID: ***@***.***&gt;

2024-06-18 17:05 UTC, haslinghuis commented on configs/YYRC-EAGLEF722V0
> +#define USE_BARO
@tianv2mu0897 please correct.

2024-06-18 21:59 UTC, tianv2mu0897 commented
YES,Is OK.





------------------ Original ------------------
From: Mark Haslinghuis ***@***.***&gt;
Date: Wed,Jun 19,2024 1:05 AM
To: betaflight/config ***@***.***&gt;
Cc: tianmu0897 ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [betaflight/config] Create YYRC-EAGLEF722 (PR #465)





 
@haslinghuis commented on this pull request.
 
 
In configs/YYRC-EAGLEF722V0:
 &gt; +#define GYRO_1_CS_PIN PA0 +#define USB_DETECT_PIN PA10 +#define PULLDOWN_PIN_UART1 PC0 + +#define TIMER_PIN_MAPPING \ +    TIMER_PIN_MAP( 0, PB9 , 2, -1) \ +    TIMER_PIN_MAP( 1, PC8 , 2,  0) \ +    TIMER_PIN_MAP( 2, PC9 , 2,  0) \ +    TIMER_PIN_MAP( 3, PA8 , 1,  0) \ +    TIMER_PIN_MAP( 4, PA9 , 1,  0) \ +    TIMER_PIN_MAP( 6, PB3 , 1,  0) \ + +#define ADC1_DMA_OPT        0 + +#define MAG_I2C_INSTANCE (I2CDEV_1) +#define USE_BARO  
@tianv2mu0897 please correct.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID: ***@***.***&gt;

2024-06-18 22:43 UTC, haslinghuis commented on configs/YYRC-EAGLEF722V0
> +#define PULLDOWN_PIN_UART1 PC0
Sorry found one more ;) This pin does not exist.
```suggestion
```

2024-06-18 22:46 UTC, tianv2mu0897 commented
OK





------------------ Original ------------------
From: Mark Haslinghuis ***@***.***&gt;
Date: Wed,Jun 19,2024 6:43 AM
To: betaflight/config ***@***.***&gt;
Cc: tianmu0897 ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [betaflight/config] Create YYRC-EAGLEF722 (PR #465)

2024-06-18 22:50 UTC, tianv2mu0897 commented
It is update





------------------ Original ------------------
From: Mark Haslinghuis ***@***.***&gt;
Date: Wed,Jun 19,2024 6:43 AM
To: betaflight/config ***@***.***&gt;
Cc: tianmu0897 ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [betaflight/config] Create YYRC-EAGLEF722 (PR #465)





 
@haslinghuis commented on this pull request.
 
 
In configs/YYRC-EAGLEF722V0:
 &gt; +#define SPI2_SCK_PIN PB13 +#define SPI3_SCK_PIN PC10 +#define SPI1_SDI_PIN PA6 +#define SPI2_SDI_PIN PB14 +#define SPI3_SDI_PIN B4 +#define SPI1_SDO_PIN PA7 +#define SPI2_SDO_PIN PB15 +#define SPI3_SDO_PIN PB5 +#define ADC_VBAT_PIN PB0 +#define ADC_CURR_PIN PC3 +#define FLASH_CS_PIN PB12 +#define MAX7456_SPI_CS_PIN PA15 +#define GYRO_1_EXTI_PIN PC4 +#define GYRO_1_CS_PIN PA0 +#define USB_DETECT_PIN PA10 +#define PULLDOWN_PIN_UART1 PC0  
Sorry found one more ;) This pin does not exist.
 ⬇️ Suggested change -#define PULLDOWN_PIN_UART1 PC0  
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID: ***@***.***&gt;

2024-06-19 00:00 UTC, tianv2mu0897 commented
OK,


正在使用发音


I will contact @sugaark;thank you.





------------------ Original ------------------
From: nerdCopter ***@***.***&gt;
Date: Tue,Jun 18,2024 10:29 PM
To: betaflight/config ***@***.***&gt;
Cc: tianmu0897 ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [betaflight/config] Create YYRC-EAGLEF722 (PR #465)





 
@tianv2mu0897 , may need to provide schematics and samples to dev-team.  may need to join Discord and contact @sugaarK for such.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID: ***@***.***&gt;

2024-06-19 21:09 UTC, haslinghuis commented on configs/YYRC-EAGLEF722
> +#define USE_BARO
```suggestion
#define BARO_I2C_INSTANCE (I2CDEV_1)
```

2024-06-19 21:09 UTC, haslinghuis approved these changes

2024-06-19 21:10 UTC, haslinghuis commented on configs/YYRC-EAGLEF722
> +    TIMER_PIN_MAP( 6, PB3 , 1,  0) \
```suggestion
    TIMER_PIN_MAP( 6, PB3 , 1,  0)
```

2024-06-19 21:11 UTC, haslinghuis commented on configs/YYRC-EAGLEF722
> ++#define PINIO2_BOX 40
```suggestion
```

2024-06-19 21:14 UTC, tianv2mu0897 commented
OK,I will update.Thank you.







------------------ Original ------------------
From: Mark Haslinghuis ***@***.***&gt;
Date: Thu,Jun 20,2024 5:09 AM
To: betaflight/config ***@***.***&gt;
Cc: tianmu0897 ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [betaflight/config] Create YYRC-EAGLEF722 (PR #465)





 
@haslinghuis commented on this pull request.
 
 
In configs/YYRC-EAGLEF722:
 &gt; +#define GYRO_1_CS_PIN PA0 +#define USB_DETECT_PIN PA10 +#define PULLDOWN_PIN PC0 + +#define TIMER_PIN_MAPPING \ +    TIMER_PIN_MAP( 0, PB9 , 2, -1) \ +    TIMER_PIN_MAP( 1, PC8 , 2,  0) \ +    TIMER_PIN_MAP( 2, PC9 , 2,  0) \ +    TIMER_PIN_MAP( 3, PA8 , 1,  0) \ +    TIMER_PIN_MAP( 4, PA9 , 1,  0) \ +    TIMER_PIN_MAP( 6, PB3 , 1,  0) \ + +#define ADC1_DMA_OPT        0 + +#define MAG_I2C_INSTANCE (I2CDEV_1) +#define USE_BARO  ⬇️ Suggested change -#define USE_BARO +#define BARO_I2C_INSTANCE (I2CDEV_1)  
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID: ***@***.***&gt;

2024-06-19 21:15 UTC, haslinghuis commented
Have made the updates already

2024-06-19 21:16 UTC, tianv2mu0897 commented
OK,I will update it;





------------------ Original ------------------
From: Mark Haslinghuis ***@***.***&gt;
Date: Thu,Jun 20,2024 5:11 AM
To: betaflight/config ***@***.***&gt;
Cc: tianmu0897 ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [betaflight/config] Create YYRC-EAGLEF722 (PR #465)





 
@haslinghuis commented on this pull request.
 
 
In configs/YYRC-EAGLEF722:
 &gt; +#define ADC_VBAT_PIN PB0 +#define ADC_CURR_PIN PC3 +#define FLASH_CS_PIN PB12 +#define MAX7456_SPI_CS_PIN PA15 +#define GYRO_1_EXTI_PIN PC4 +#define GYRO_1_CS_PIN PA0 +#define USB_DETECT_PIN PA10 +#define PULLDOWN_PIN PC0 + +#define TIMER_PIN_MAPPING \ +    TIMER_PIN_MAP( 0, PB9 , 2, -1) \ +    TIMER_PIN_MAP( 1, PC8 , 2,  0) \ +    TIMER_PIN_MAP( 2, PC9 , 2,  0) \ +    TIMER_PIN_MAP( 3, PA8 , 1,  0) \ +    TIMER_PIN_MAP( 4, PA9 , 1,  0) \ +    TIMER_PIN_MAP( 6, PB3 , 1,  0) \  ⬇️ Suggested change -    TIMER_PIN_MAP( 6, PB3 , 1,  0) \ +    TIMER_PIN_MAP( 6, PB3 , 1,  0)  
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID: ***@***.***&gt;

2024-06-19 21:17 UTC, tianv2mu0897 commented
OK,I will update it；





------------------ Original ------------------
From: Mark Haslinghuis ***@***.***&gt;
Date: Thu,Jun 20,2024 5:12 AM
To: betaflight/config ***@***.***&gt;
Cc: tianmu0897 ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [betaflight/config] Create YYRC-EAGLEF722 (PR #465)





 
@haslinghuis commented on this pull request.
 
 
In configs/YYRC-EAGLEF722:
 &gt; + ++#define PINIO2_CONFIG 129 ++#define PINIO1_BOX 0 ++#define PINIO2_BOX 40  ⬇️ Suggested change - -+#define PINIO2_CONFIG 129 -+#define PINIO1_BOX 0 -+#define PINIO2_BOX 40  
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID: ***@***.***&gt;

2024-06-19 21:18 UTC, haslinghuis commented on configs/YYRC-EAGLEF722
> +#define PULLDOWN_PIN PC0
```suggestion
```

2024-06-19 21:20 UTC, tianv2mu0897 commented
It is be use





------------------ Original ------------------
From: Mark Haslinghuis ***@***.***&gt;
Date: Thu,Jun 20,2024 5:19 AM
To: betaflight/config ***@***.***&gt;
Cc: tianmu0897 ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [betaflight/config] Create YYRC-EAGLEF722 (PR #465)





 
@haslinghuis commented on this pull request.
 
 
In configs/YYRC-EAGLEF722:
 &gt; +#define SPI2_SCK_PIN PB13 +#define SPI3_SCK_PIN PC10 +#define SPI1_SDI_PIN PA6 +#define SPI2_SDI_PIN PB14 +#define SPI3_SDI_PIN B4 +#define SPI1_SDO_PIN PA7 +#define SPI2_SDO_PIN PB15 +#define SPI3_SDO_PIN PB5 +#define ADC_VBAT_PIN PB0 +#define ADC_CURR_PIN PC3 +#define FLASH_CS_PIN PB12 +#define MAX7456_SPI_CS_PIN PA15 +#define GYRO_1_EXTI_PIN PC4 +#define GYRO_1_CS_PIN PA0 +#define USB_DETECT_PIN PA10 +#define PULLDOWN_PIN PC0  ⬇️ Suggested change -#define PULLDOWN_PIN PC0  
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID: ***@***.***&gt;

2024-06-19 22:16 UTC, ot0tot reviewed
Two minor changes suggested, otherwise it looks good!

2024-06-19 22:16 UTC, ot0tot commented on configs/YYRC-EAGLEF722
> +#define DEFAULT_DSHOT_BURST DSHOT_DMAR_ON
No need to set DShot burst to On. Delete this or set to AUTO. 
Consider adding `#define DEFAULT_DSHOT_BITBANG DSHOT_BITBANG_ON`.

2024-06-20 02:10 UTC, tianv2mu0897 commented
OK,I will update it,Thank you!





------------------ Original ------------------
From: ot0tot ***@***.***&gt;
Date: Thu,Jun 20,2024 6:17 AM
To: betaflight/config ***@***.***&gt;
Cc: tianmu0897 ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [betaflight/config] Create YYRC-EAGLEF722 (PR #465)





 
@ot0tot commented on this pull request.
 
Two minor changes suggested, otherwise it looks good!

 
In configs/YYRC-EAGLEF722:
 &gt; +#define USE_GYRO +#define USE_GYRO_SPI_MPU6000 +#define USE_GYRO_SPI_ICM42688P +#define USE_BARO +#define USE_BARO_BMP280 +#define USE_BARO_DPS310 +#define USE_FLASH +#define USE_FLASH_M25P16 +#define USE_MAX7456 + +#define BEEPER_PIN PC13 +#define MOTOR1_PIN PC9 +#define MOTOR2_PIN PC8 +#define MOTOR3_PIN PA8 +#define MOTOR4_PIN PA9 +#define RX_PPM_PIN PB9  
Does this FC actually have a PPM input pin?
 
 
In configs/YYRC-EAGLEF722:
 &gt; +#define TIMER_PIN_MAPPING \ +    TIMER_PIN_MAP( 0, PB9 , 2, -1) \ +    TIMER_PIN_MAP( 1, PC8 , 2,  0) \ +    TIMER_PIN_MAP( 2, PC9 , 2,  0) \ +    TIMER_PIN_MAP( 3, PA8 , 1,  0) \ +    TIMER_PIN_MAP( 4, PA9 , 1,  0) \ +    TIMER_PIN_MAP( 6, PB3 , 1,  0) + +#define ADC1_DMA_OPT        0 + +#define MAG_I2C_INSTANCE (I2CDEV_1) +#define BARO_I2C_INSTANCE (I2CDEV_1) + +#define ADC_INSTANCE ADC1 +#define DEFAULT_BLACKBOX_DEVICE     BLACKBOX_DEVICE_FLASH +#define DEFAULT_DSHOT_BURST DSHOT_DMAR_ON  
No need to set DShot burst to On. Delete this or set to AUTO.
 Consider adding #define DEFAULT_DSHOT_BITBANG DSHOT_BITBANG_ON.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID: ***@***.***&gt;

2024-06-20 03:45 UTC, tianv2mu0897 commented
hello:
hello:&nbsp; &nbsp; &nbsp;
&nbsp; &nbsp; &nbsp;i am join in discord,how i will contact he? what is his discord name?can you tell me and his discord name;Thank you!




【天v2幕】
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "betaflight/config"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年6月18日(星期二) 晚上10:29
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [betaflight/config] Create YYRC-EAGLEF722 (PR #465)





 
@tianv2mu0897 , may need to provide schematics and samples to dev-team.  may need to join Discord and contact @sugaarK for such.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID: ***@***.***&gt;

2024-06-28 00:55 UTC, tianv2mu0897 commented
hello:
&nbsp; &nbsp; &nbsp; betafligth/config is When can it be merged into BETAFLIGHT！thank you!




【天v2幕】
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "betaflight/config"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年6月20日(星期四) 上午6:17
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [betaflight/config] Create YYRC-EAGLEF722 (PR #465)





 
@ot0tot commented on this pull request.
 
Two minor changes suggested, otherwise it looks good!

 
In configs/YYRC-EAGLEF722:
 &gt; +#define USE_GYRO +#define USE_GYRO_SPI_MPU6000 +#define USE_GYRO_SPI_ICM42688P +#define USE_BARO +#define USE_BARO_BMP280 +#define USE_BARO_DPS310 +#define USE_FLASH +#define USE_FLASH_M25P16 +#define USE_MAX7456 + +#define BEEPER_PIN PC13 +#define MOTOR1_PIN PC9 +#define MOTOR2_PIN PC8 +#define MOTOR3_PIN PA8 +#define MOTOR4_PIN PA9 +#define RX_PPM_PIN PB9  
Does this FC actually have a PPM input pin?
 
 
In configs/YYRC-EAGLEF722:
 &gt; +#define TIMER_PIN_MAPPING \ +    TIMER_PIN_MAP( 0, PB9 , 2, -1) \ +    TIMER_PIN_MAP( 1, PC8 , 2,  0) \ +    TIMER_PIN_MAP( 2, PC9 , 2,  0) \ +    TIMER_PIN_MAP( 3, PA8 , 1,  0) \ +    TIMER_PIN_MAP( 4, PA9 , 1,  0) \ +    TIMER_PIN_MAP( 6, PB3 , 1,  0) + +#define ADC1_DMA_OPT        0 + +#define MAG_I2C_INSTANCE (I2CDEV_1) +#define BARO_I2C_INSTANCE (I2CDEV_1) + +#define ADC_INSTANCE ADC1 +#define DEFAULT_BLACKBOX_DEVICE     BLACKBOX_DEVICE_FLASH +#define DEFAULT_DSHOT_BURST DSHOT_DMAR_ON  
No need to set DShot burst to On. Delete this or set to AUTO.
 Consider adding #define DEFAULT_DSHOT_BITBANG DSHOT_BITBANG_ON.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID: ***@***.***&gt;

2024-06-28 01:20 UTC, ot0tot commented
Awaiting schematics and dev samples. Have you joined the Discord and contacted @sugaarK ?

2024-06-28 02:02 UTC, tianv2mu0897 commented
I have joined the discord,But I didn't get in touch ***@***.***&nbsp;?





【天v2幕】
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "betaflight/config"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年6月28日(星期五) 上午9:20
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [betaflight/config] Create YYRC-EAGLEF722 (PR #465)





 
Awaiting schematics and dev samples. Have you joined the Discord and contacted @sugaarK ?
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID: ***@***.***&gt;

2024-07-12 02:17 UTC, sugaarK approved these changes

2024-07-12 02:18 UTC, tianv2mu0897 commented
邮件已收到，谢谢！

2024-07-12 09:53 UTC, haslinghuis requested changes
Need to change filename to match board_name

2024-07-12 09:53 UTC, haslinghuis commented on configs/YYRC-EAGLEF722
> +#define ADC_INSTANCE ADC1
ADC1 is default
```suggestion
```

2024-07-12 13:00 UTC, nerdCopter commented
> Need to change filename to match board_name

@tianv2mu0897 , in your repo, (assuming linux)
```
mkdir configs/EAGLEF722
git mv configs/YYRC-EAGLEF722 configs/EAGLEF722/config.h
```
then commit/push

2024-07-12 13:51 UTC, nerdCopter commented
https://github.com/betaflight/config/pull/465/commits/83488d46646a1a3fdfcf9f7d6532368d49554f88 is still not proper, it should be `EAGLEF722/config.h`

2024-07-12 14:17 UTC, tianv2mu0897 commented
hello:
&nbsp; &nbsp; &nbsp;&nbsp;How do I operate on the page?Thank you!




How do I operate on the page

【天v2幕】
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "betaflight/config"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年7月12日(星期五) 晚上9:51
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [betaflight/config] Create YYRC-EAGLEF722 (PR #465)





 
83488d4 is still not proper, it should be EAGLEF722/config.h
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID: ***@***.***&gt;

2024-07-12 14:17 UTC, tianv2mu0897 commented
hello:
&nbsp; &nbsp; &nbsp;&nbsp;How do I operate on the page?Thank you!



【天v2幕】
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "betaflight/config"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年7月12日(星期五) 晚上9:51
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [betaflight/config] Create YYRC-EAGLEF722 (PR #465)





 
83488d4 is still not proper, it should be EAGLEF722/config.h
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID: ***@***.***&gt;

2024-07-12 14:28 UTC, nerdCopter commented
- not possible via web-interface.
- i fixed and pushed

2024-07-12 14:29 UTC, nerdCopter commented
@haslinghuis , please repeat last suggestion from new file. TY

2024-07-12 14:31 UTC, tianv2mu0897 commented
Thank you very much;




【天v2幕】
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "betaflight/config"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年7月12日(星期五) 晚上10:29
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [betaflight/config] Create YYRC-EAGLEF722 (PR #465)





  
not possible via web-interface.
 
i fixed and pushed
  
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID: ***@***.***&gt;

2024-07-12 14:38 UTC, haslinghuis requested changes

2024-07-12 14:38 UTC, haslinghuis commented on configs/EAGLEF722/config.h
> +#define ADC_INSTANCE ADC1
ADC1 is default instance
```suggestion
```

2024-07-12 14:39 UTC, haslinghuis approved these changes

2024-07-12 14:39 UTC, nerdCopter approved these changes

2024-07-12 14:40 UTC, haslinghuis commented on configs/YYRC-EAGLEF722
> +#define DEFAULT_DSHOT_BURST DSHOT_DMAR_ON
```suggestion
#define DEFAULT_DSHOT_BITBANG DSHOT_BITBANG_ON
```

2024-07-12 14:42 UTC, merged