Add BROTHERHOBBYF405V3
betaflight/config pull request #518
Opened 2024-08-12 08:26 UTC by H-ChuWu

Add new target BROTHERHOBBYF405V3

2024-08-12 21:30 UTC, haslinghuis requested changes
Quick review - did not check dma / timers

2024-08-12 21:30 UTC, haslinghuis commented on configs/BROTHERHOBBYF405V3/config.h
> +#define BOARD_NAME        BrotherHobbyF405V3
```suggestion
#define BOARD_NAME        BROTHERHOBBYF405V3
```

2024-08-12 21:30 UTC, haslinghuis commented on configs/BROTHERHOBBYF405V3/config.h
> +#define PINIO1_PIN 				PC14
```suggestion
#define PINIO1_PIN              PC14
```

2024-08-12 21:30 UTC, haslinghuis commented on configs/BROTHERHOBBYF405V3/config.h
> +#define DASHBOARD_I2C_INSTANCE 				(I2CDEV_1)
Can be removed
```suggestion
```

2024-08-13 01:15 UTC, H-ChuWu commented
> 快速回顾 - 没有检查 dma / 计时器

![Uploading b461a803aa023076ab2e92be773d831.png…]()

2024-08-13 03:55 UTC, ot0tot requested changes

2024-08-13 03:55 UTC, ot0tot commented on configs/BROTHERHOBBYF405V3/config.h
> + 	TIMER_PIN_MAP(0, PA8, 1, 0) \
Change to `TIMER_PIN_MAP(0, PA8, 1, 1) \`

2024-08-13 03:55 UTC, ot0tot commented on configs/BROTHERHOBBYF405V3/config.h
> + 	TIMER_PIN_MAP(3, PB11, 1, 0) \
Change to `TIMER_PIN_MAP(3, PB11, 1, 1) \`

2024-08-13 03:55 UTC, ot0tot commented on configs/BROTHERHOBBYF405V3/config.h
> +#define SPI2_TX_DMA_OPT     0
Delete `#define SPI2_TX_DMA_OPT     0`

2024-08-13 07:08 UTC, haslinghuis requested changes

2024-08-13 07:08 UTC, haslinghuis commented on configs/BROTHERHOBBYF405V3/config.h
> +#define BOARD_NAME        BHF405V3
Does not match 

![image](https://github.com/user-attachments/assets/7a861b3f-259b-471a-97f4-02c7a48acc00)

2024-08-13 07:40 UTC, ot0tot approved these changes

2024-08-13 07:52 UTC, merged