add hdzero h7 target
betaflight/config pull request #525
Opened 2024-08-17 19:35 UTC by freasy

Add HDZERO H7 target

2024-08-17 19:50 UTC, haslinghuis requested changes

2024-08-17 19:50 UTC, haslinghuis commented on configs/HDZEROH743R/config.h
> +#define USE_SPI_GYRO
This is default
```suggestion
```

2024-08-17 19:50 UTC, haslinghuis commented on configs/HDZEROH743R/config.h
> +#define GYRO_2_SPI_INSTANCE SPI1
No return on EOF
```suggestion
#define GYRO_2_SPI_INSTANCE SPI1

```

2024-08-18 04:08 UTC, ot0tot commented on configs/HDZEROH743R/config.h
> +    TIMER_PIN_MAP(  3, MOTOR4_PIN,  2,  0 ) \
Why are these on TIM8? If you move motors 3 and 4 to TIM3, only one TIMUP resource is required for burst DMA.

2024-08-18 04:09 UTC, ot0tot commented on configs/HDZEROH743R/config.h
> +#define USE_GYRO_SPI_MPU6500
Why include MPU6500?

2024-08-18 04:10 UTC, ot0tot commented on configs/HDZEROH743R/config.h
> +#define SPI1_RX_DMA_OPT 7
Not needed

2024-08-18 04:14 UTC, ot0tot commented on configs/HDZEROH743R/config.h
> +#define USE_ACC_SPI_MPU6500
```suggestion

```

2024-08-18 04:16 UTC, ot0tot commented on configs/HDZEROH743R/config.h
> +    TIMER_PIN_MAP(  3, MOTOR4_PIN,  2,  0 ) \
Why are these on TIM8? If you move motors 3 and 4 to TIM3, only one TIMUP resource is required for burst DMA.
```suggestion
    TIMER_PIN_MAP(  2, MOTOR3_PIN,  1,  0 ) \
    TIMER_PIN_MAP(  3, MOTOR4_PIN,  1,  0 ) \
```

2024-08-18 04:17 UTC, ot0tot commented on configs/HDZEROH743R/config.h
> +    TIMER_PIN_MAP(  3, MOTOR4_PIN,  2,  0 ) \
Why are these on TIM8? If you move motors 3 and 4 to TIM3, only one TIMUP resource is required for burst DMA.
```suggestion
    TIMER_PIN_MAP(  2, MOTOR3_PIN,  1,  0 ) \
    TIMER_PIN_MAP(  3, MOTOR4_PIN,  1,  0 ) \
```

2024-08-18 04:18 UTC, ot0tot commented on configs/HDZEROH743R/config.h
> +#define DEFAULT_CURRENT_METER_SCALE 100
Does this need to be set? Does this FC come with an ESC?

2024-08-18 14:40 UTC, sugaarK commented on configs/HDZEROH743R/config.h
> +#define USE_GYRO_SPI_MPU6500
I won't let them make a 6500 version!

2024-09-16 03:36 UTC, sugaarK commented
@freasy can you address the changes? or are you waiting for samples?

2024-09-16 04:12 UTC, freasy commented
> @freasy can you address the changes? or are you waiting for samples?

Samples are on the way

2024-12-09 14:58 UTC, haslinghuis reviewed
No barometer ?

2024-12-09 14:58 UTC, haslinghuis commented on configs/HDZEROH743R/config.h
> +#define USE_TELEMETRY
This is defined by RX protocol
```suggestion
```

2024-12-09 15:08 UTC, ot0tot commented on configs/HDZEROH743R/config.h
> +#define TIMUP8_DMA_OPT 0
```suggestion
#define TIMER_PIN_MAPPING \
    TIMER_PIN_MAP(  0, MOTOR1_PIN,  1,  0 ) /* TIM3 CH1 */ \
    TIMER_PIN_MAP(  1, MOTOR2_PIN,  1,  1 ) /* TIM3 CH2 */ \
    TIMER_PIN_MAP(  2, MOTOR3_PIN,  1,  2 ) /* TIM3 CH3 */ \
    TIMER_PIN_MAP(  3, MOTOR4_PIN,  1,  3 ) /* TIM3 CH4 */ \
    TIMER_PIN_MAP(  4, LED_STRIP_PIN,  1,  4 ) /* TIM1 CH3 */ \
    TIMER_PIN_MAP(  5, BEEPER_PIN,  1,  -1) /* TIM4 CH1 */

#define ADC1_DMA_OPT 8
#define ADC2_DMA_OPT 9
#define ADC3_DMA_OPT 10

#define TIMUP1_DMA_OPT 0
#define TIMUP3_DMA_OPT 5
#define TIMUP4_DMA_OPT 0
#define TIMUP5_DMA_OPT 0
#define TIMUP8_DMA_OPT 0
```

2024-12-09 15:09 UTC, ot0tot commented on configs/HDZEROH743R/config.h
> +#define LED1_PIN PC14
PC14 should not be used to drive LEDs per the datasheet

2024-12-10 13:29 UTC, haslinghuis approved these changes

2024-12-10 13:55 UTC, ot0tot commented on configs/HDZEROH743R/config.h
> +
Include TIMUP DMA assignment so burst DMA works also. 
```suggestion

#define TIMUP3_DMA_OPT      5

```

2024-12-10 13:57 UTC, ot0tot commented
Why are there two gyros defined? It appears the FC only has one gyro?

2024-12-10 22:28 UTC, sugaarK commented
> Why are there two gyros defined? It appears the FC only has one gyro?

Comes in 2 flavours

2024-12-13 16:35 UTC, merged