add new target StellarF7 Dual
betaflight/config pull request #595
Opened 2024-10-20 07:17 UTC by cvetaevvitaliy

Add new target StellarF7 Dual

2024-10-22 12:13 UTC, haslinghuis requested changes

2024-10-22 12:13 UTC, haslinghuis commented on configs/STELLARF7_DUAL/config.h
> +                          TIMER_PIN_MAP( 8, PB3, 1, 0 ) \
Servo does not need DMA.
```suggestion
                          TIMER_PIN_MAP( 8, PB3, 1, -1) \
```

2024-10-22 12:13 UTC, haslinghuis commented on configs/STELLARF7_DUAL/config.h
> +#define FLASH_SPI_INSTANCE SPI2
Sharing SPI

2024-10-22 12:13 UTC, haslinghuis commented on configs/STELLARF7_DUAL/config.h
> +#define ADC_INSTANCE ADC1
ADC1 is default instance.
```suggestion
```

2024-10-23 03:21 UTC, sugaarK commented on configs/STELLARF7_DUAL/config.h
> +#define FLASH_SPI_INSTANCE SPI2
> Sharing SPI

@cvetaevvitaliy  we don't allow this

2024-10-23 10:21 UTC, haslinghuis commented on configs/STELLARF7_DUAL_HD/config.h
> +#define MAX7456_SPI_CS_PIN PC3
MAX7456 has been removed
```suggestion
```

2024-10-23 10:32 UTC, haslinghuis approved these changes

2024-10-23 11:43 UTC, merged