Add SPEEDYBEEF405WING target
betaflight/config pull request #608
Opened 2024-11-14 01:32 UTC by ot0tot

2024-11-14 10:51 UTC, haslinghuis approved these changes

2024-11-14 10:51 UTC, haslinghuis commented on configs/SPEEDYBEEF405WING/config.h
> +	TIMER_PIN_MAP( 5, PA8 , 1,  0)
```suggestion
    TIMER_PIN_MAP( 5, PA15, 1, -1) \
    TIMER_PIN_MAP( 5, PB10, 1, -1) \
    TIMER_PIN_MAP( 5, PA8 , 1,  0) 
```

2024-12-24 00:14 UTC, haslinghuis commented
@ot0tot anything needed to add this ?

2024-12-24 00:21 UTC, limonspb approved these changes

2024-12-24 03:57 UTC, ot0tot commented
> @ot0tot anything needed to add this ?

The major issue is the EXT1 pin is not connected, so there is no way to sync the gyro with the PID loop. I have a FC, but have but been able to test the target yet. 
If you have a Wing FC, please feel free to test and provide feedback. If any of the devs have a way to validate the PID loop rate performance, that would be great also.

2024-12-25 21:35 UTC, SteveCEvans commented
The lack of the interrupt isn't a major issue. The consequence is increased jitter and thus poorer filter performance. Also DMA transfers can’t be initiated ahead of the gyro task being called, so there’s a performance hit. We can live without it, but it would certainly be better with.

2025-01-04 19:26 UTC, haslinghuis commented
@ot0tot 
- Like to merge this.
- We are aware of limitations but this is board is already in production.
- Limitations won't be a big deal for wings - but we would not accept this for new designs.
- New designs will have to deal with new design requirements and standards we set.

2025-01-05 06:45 UTC, limonspb commented
@ot0tot 
i've tried to flash it, everything seems to be working. except SD card for blackbox.

i've tried to add:
```
#define SDCARD_DETECT_INVERTED
#define USE_SDCARD_SPI
#define SDCARD_SPI_INSTANCE SPI3
```
and removed `#define FLASH_SPI_INSTANCE             SPI3`, `#define USE_FLASH`, `#define USE_FLASH_W25Q128FV` but status shows `SD card: Not configured` no matter what.
And i can't select SD card for logging:
![image](https://github.com/user-attachments/assets/48bbd440-d5fc-4a1a-bcf9-f54c906b936e)

maybe it should be something else, not SPI3? Could you plz help.

2025-01-05 16:35 UTC, haslinghuis commented
The mini board does not seem to have flash, also updated SDC related defines with same results.

2025-01-05 18:42 UTC, limonspb commented
> * The mini board does not seem to have flash, also updated SDC related defines with same results.
> * Do we need the `SDCARD_DETECT_PIN` ?

MINI board also have SD card slot. And it fails to connect to it with the same error.

2025-01-06 02:49 UTC, ot0tot commented on configs/SPEEDYBEEF405WING/config.h
> +#define FLASH_SPI_INSTANCE             SPI3
```suggestion
#define SDCARD_SPI_INSTANCE             SPI3
```

2025-01-06 05:42 UTC, limonspb submitted a review, later dismissed
i think these suggestions are correct, but it still doesn't make SD card to work...

2025-01-06 05:42 UTC, limonspb commented on configs/SPEEDYBEEF405WING/config.h
> +#define USE_FLASH_W25Q128FV
`#define USE_FLASH` and `#define USE_FLASH_W25Q128FV` are not needed as far as I understand

2025-01-06 05:42 UTC, limonspb commented on configs/SPEEDYBEEF405WING/config.h
> +#define SDCARD_CS_PIN      PC14
`#define SDCARD_SPI_CS_PIN  PC14` instead of `#define SDCARD_CS_PIN PC14`

2025-01-06 06:12 UTC, ot0tot commented
Came across this issue: https://github.com/betaflight/betaflight/issues/12958

2025-01-06 06:26 UTC, ot0tot commented
SD card works in BF 4.2.11, but not in any later versions. 

```MCU F40X Clock=168MHz (PLLP-HSE), Vref=3.28V, Core temp=35degC
Stack size: 2048, Stack address: 0x1000fff0
Config size: 3960, Max available config: 16384
Gyros detected:

OSD: MAX7456
System Uptime: 29 seconds, Current Time: 2025-01-06T06:25:11.432+00:00
CPU:1%, cycle time: 0, GYRO rate: 0, RX rate: 33, System rate: 10
Voltage: 1 * 0.01V (0S battery - NOT PRESENT)
I2C Errors: 0
SD card: Manufacturer 0x9e, 3914752kB, 11/2016, v0.2, '     '
Filesystem: Ready
Arming disable flags: NOGYRO RXLOSS CLI MSP```

![image](https://github.com/user-attachments/assets/898db05a-3476-4990-9c17-7cc8d2d57c94)

2025-01-07 03:29 UTC, limonspb commented
this commit causing issues for this FC sdcard: 87c8847c13d7f759548c2384e400d2bc387b159a
so its this PR: https://github.com/betaflight/betaflight/pull/10705

2025-01-10 20:09 UTC, limonspb commented
SD card issue resolved here by @SteveCEvans 
https://github.com/betaflight/betaflight/pull/14142

2025-01-10 20:22 UTC, haslinghuis requested changes

2025-01-10 20:22 UTC, haslinghuis commented on configs/SPEEDYBEEF405WING/config.h
> +//#define USE_FLASH_W25Q128FV
```suggestion
```

2025-01-10 20:22 UTC, haslinghuis commented on configs/SPEEDYBEEF405WING/config.h
> +#define USE_BARO_SPL06
Does not exist
```suggestion
```

2025-01-10 20:22 UTC, haslinghuis commented on configs/SPEEDYBEEF405WING/config.h
> +//#define GYRO_1_EXTI_PIN  PC4
Not used
```suggestion
```

2025-01-10 20:22 UTC, haslinghuis commented on configs/SPEEDYBEEF405WING/config.h
> +//#define DEFAULT_CURRENT_METER_OFFSET -500
Remove or verify
```suggestion
```

2025-01-10 20:22 UTC, haslinghuis commented on configs/SPEEDYBEEF405WING/config.h
> +//#define FLASH_SPI_INSTANCE             SPI3
Unused
```suggestion
```

2025-01-10 21:22 UTC, ot0tot commented
Since this FC lacks the gyro interrupt connection, should we include a line in the define to limit the PID loop rate to 4kHz or 2kHz?
```
#define DEFAULT_PID_PROCESS_DENOM 2
```

2025-01-10 21:41 UTC, haslinghuis commented on configs/SPEEDYBEEF405WING/config.h
> +#define GYRO_1_ALIGN_YAW               2700
Using preset here. `GYRO_ALIGN_YAW` is automatically set and only applies when using `GYRO_1_ALIGN CUSTOM`
```suggestion
```

2025-01-10 22:08 UTC, limonspb commented
> Since this FC lacks the gyro interrupt connection, should we include a line in the define to limit the PID loop rate to 4kHz or 2kHz?
> 
> ```
> #define DEFAULT_PID_PROCESS_DENOM 2
> ```

Let's limit with 4k first and see how that goes?

2025-01-11 18:14 UTC, ot0tot commented
I think this is good to go now. @limonspb reports tested and everything working properly. 

Please review and merge when able.

2025-01-11 19:18 UTC, haslinghuis approved these changes

2025-01-12 02:18 UTC, limonspb commented
> I think this is good to go now. @limonspb reports tested and everything working properly.
> 
> Please review and merge when able.

Flies amazing! Thanks!

https://github.com/user-attachments/assets/76677d19-a13c-4208-8553-1c30fa527e97

2025-01-13 15:07 UTC, nerdCopter approved these changes

2025-01-13 15:09 UTC, merged