Add DAKEFPVF405X8
betaflight/config pull request #612
Opened 2024-11-19 14:32 UTC by ThanYangFPV

Schematics and configuration files have been emailed to cloudtargets@betaflight.com.

Please review. Thank you.

2024-11-19 14:50 UTC, haslinghuis requested changes
Have not checked timers and DMA

2024-11-19 14:50 UTC, haslinghuis commented on configs/DAKEFPVF405X8/config.h
> +
```suggestion
#define TIMER_PIN_MAPPING \
        TIMER_PIN_MAP( 0, MOTOR1_PIN        , 2,  0) \
        TIMER_PIN_MAP( 1, MOTOR2_PIN        , 2,  1) \
        TIMER_PIN_MAP( 2, MOTOR3_PIN        , 2,  1) \
        TIMER_PIN_MAP( 3, MOTOR4_PIN        , 2,  0) \
        TIMER_PIN_MAP( 4, MOTOR5_PIN        , 1,  0) \
        TIMER_PIN_MAP( 5, MOTOR6_PIN        , 1,  0) \
	TIMER_PIN_MAP( 6, MOTOR7_PIN        , 1,  0) \
	TIMER_PIN_MAP( 7, MOTOR8_PIN        , 1,  0) \
	TIMER_PIN_MAP( 8, LED_STRIP_PN      , 2,  0) \
	TIMER_PIN_MAP( 9, CAMERA_CONTROL_PIN, 2, -1)
```

2024-11-19 14:50 UTC, haslinghuis commented on configs/DAKEFPVF405X8/config.h
> +#define USE_CAMERA_CONTROL
```suggestion
#ifndef USE_CAMERA_CONTROL
#define USE_CAMERA_CONTROL
#endif
```

2024-11-26 05:42 UTC, ot0tot commented on configs/DAKEFPVF405X8/config.h
> +#define LED1_PIN             PC15
```suggestion
#define LED0_PIN             PC14
#define LED1_PIN             PC15
```
These pins cannot be used to drive LEDs

2024-11-26 05:43 UTC, ot0tot commented
I think we have decided the F405 cannot reliably support 8 motor outputs. Recommend H743 for X8, or reduce the number of motor outputs to use F405.

2024-11-30 03:40 UTC, ThanYangFPV commented
> I think we have decided the F405 cannot reliably support 8 motor outputs. Recommend H743 for X8, or reduce the number of motor outputs to use F405.

OK. I will close this PR.
Thank you.

2024-11-30 03:40 UTC, closed without merging