Add DAKEFPVF722X8
betaflight/config pull request #613
Opened 2024-11-19 14:33 UTC by ThanYangFPV

Schematics and configuration files have been emailed to [cloudtargets@betaflight.com](mailto:cloudtargets@betaflight.com).

Please review. Thank you.

2024-11-19 14:51 UTC, haslinghuis requested changes

2024-11-19 14:51 UTC, haslinghuis commented on configs/DAKEFPVF722X8/config.h
> +#define USE_CAMERA_CONTROL
```suggestion
#ifndef USE_CAMERA_CONTROL
#define USE_CAMERA_CONTROL
#endif
```

2024-11-19 14:51 UTC, haslinghuis commented on configs/DAKEFPVF722X8/config.h
> +    TIMER_PIN_MAP( 9, PB0 , 2, 0)
```suggestion
    TIMER_PIN_MAP( 9, PB0 , 2, -1)
```

2024-11-26 05:44 UTC, ot0tot commented on configs/DAKEFPVF722X8/config.h
> +#define USE_ACC_SPI_MPU6500
You should not be using the 6500 in new designs 
```suggestion

```

2024-11-26 05:44 UTC, ot0tot commented on configs/DAKEFPVF722X8/config.h
> +#define USE_GYRO_SPI_MPU6500
```suggestion

```

2024-11-26 05:45 UTC, ot0tot commented on configs/DAKEFPVF722X8/config.h
> +#define LED1_PIN             PC15
These pins should not be used to drive LEDs

2024-11-26 05:55 UTC, ot0tot commented on configs/DAKEFPVF722X8/config.h
> +    TIMER_PIN_MAP( 9, PB0 , 2, -1)
Motors split between too many timers. M1-4 on TIM8, but M5-8 are on TIM1, TIM2, and TIM4.

2024-11-29 18:08 UTC, ot0tot approved these changes

2024-11-29 18:25 UTC, haslinghuis commented on configs/DAKEFPVF722X8/config.h
> +#define BARO_I2C_INSTANCE (I2CDEV_1)
```suggestion
#define BARO_I2C_INSTANCE I2CDEV_1
```

2024-11-29 18:28 UTC, haslinghuis approved these changes

2024-11-29 18:28 UTC, merged