Fix SEQUREH7V2
betaflight/config pull request #615
Opened 2024-11-24 17:45 UTC by swagprincess

- Fix motor 1 (PB4) not being assigned in timer_pin_map.
- Change the DMA field from -1 to 0 in timer_pin_map as per H7 guidelines (DMA arbiter).
- Remove unnecessary gyro drivers (difference between V1 and V2 is just the gyro).
- Add DMA definitions for TIMUP2 and 4, used for motors 5-8, for burst dshot.
- Remove unnecessary TIMUP definitions and I2C pins from timer_pin_map.
- General restructuring/legibility.

I have flown this config in my build various times and have had no problems.

2024-11-24 18:01 UTC, haslinghuis requested changes

2024-11-24 18:01 UTC, haslinghuis commented on configs/SEQUREH7V2/config.h
> +#define FLASH_SPI_INSTANCE SPI3
- No new line on EOF
```suggestion
#define FLASH_SPI_INSTANCE SPI3

```

2024-11-24 18:03 UTC, swagprincess commented
Thank you! I've seen in other targets camera control being left to 0 so I assumed it was okay

2024-11-24 18:12 UTC, swagprincess commented
somehow managed to split that into 2 commits, sigh, should be okay now

2024-11-24 21:02 UTC, haslinghuis commented on configs/SEQUREH7V2/config.h
> +#define FLASH_SPI_INSTANCE SPI3
```suggestion
#define FLASH_SPI_INSTANCE SPI3

```

2024-11-24 21:08 UTC, haslinghuis approved these changes

2024-11-25 00:20 UTC, sugaarK approved these changes

2024-11-25 00:22 UTC, merged