Remove legacy ACCGYRO driver from STM32F411DISCOVERY
betaflight/config pull request #649
Opened 2024-12-22 12:28 UTC by haslinghuis

- removing legacy accgyro drivers in preparation for https://github.com/betaflight/betaflight/pull/14087

2024-12-22 20:28 UTC, blckmn commented
I think if prefer to keep the driver...

2024-12-23 22:14 UTC, nerdCopter approved these changes

2024-12-29 06:39 UTC, blckmn requested changes
Rather than remove this gyro, acc combo why not modify them to be non legacy.

2024-12-31 19:19 UTC, haslinghuis commented
Thinking we should just purge this configuration instead - as we no longer recommend F411 designs.

2025-01-01 07:42 UTC, blckmn commented
Whilst that true... the F411 disco is still a good debugging platform for general code checking. When we stop supporting F411 entirely it'd make sense to drop it.

2025-01-17 18:29 UTC, merged