Add SKYSTARSF7RS
betaflight/config pull request #67
Opened 2023-06-13 08:56 UTC by freasy

2023-06-13 12:41 UTC, haslinghuis commented
We already have the SKYSTARSF7HDPRO target.

2023-06-14 05:47 UTC, blckmn requested changes

2023-06-14 05:47 UTC, blckmn commented on configs/SKYSTARSF7RS/config.h
> +#define BOARD_NAME        SKYSTARSF7HDPRO
Board name and directory name should match.

2023-06-14 07:57 UTC, haslinghuis commented on configs/SKYSTARSF7RS/config.h
> +#define DEFAULT_PID_PROCESS_DENOM 1
setting can be removed - as it is default
```suggestion
#define DEFAULT_PID_PROCESS_DENOM 1
```

2023-06-14 07:57 UTC, haslinghuis commented on configs/SKYSTARSF7RS/config.h
> +//TODO #define OSD_AVG_CELL_VOLTAGE_POS 2114
Remove user settings

2023-06-14 09:19 UTC, haslinghuis commented
@freasy can you please also create an unified target for this.

2023-06-15 19:52 UTC, haslinghuis approved these changes

2023-06-15 19:52 UTC, merged